### ISSUE TITLE
More work for PB !

### ISSUE THREAD

**Issue by mpariente** [fgnt/pb_bss#12]
I'm annoying, I know but [this](https://github.com/fgnt/pb_bss/blob/master/pb_bss/evaluation/wrapper.py#L91) is not really user friendly ;-)

Is paderbox open-source? I cannot find it

**Comment by boeddeker** [comment]
Sorry about that. We released recently the evaluation code.
Since the pesq license didn't allow us to publish our pesq wrapper,
we kept it internally. We will change the code to use pypesq.
This will remove the dependency on internal code.

Thank you for reporting this and sorry, that we didn't change it earlier.

Btw.: At the moment we are working on a release of the paderbox.

**Comment by LukasDrude** [comment]
I now removed the Paderbox dependency and added a test case to the wrapper. You may review the changes here:

https://github.com/fgnt/pb_bss/commit/dd7096573ce182331bddeef3e5168e886d8ffe68

**Comment by mpariente** [comment]
Looks good, I'll pull it and test it tonight. Thanks a bunch

**Comment by mpariente** [comment]
That's perfect thank you !
