### ISSUE TITLE
SI-SDR in float64 only?

### ISSUE THREAD

**Issue by mpariente** [fgnt/pb_bss#23]
Hi, 

What's the motivation behind [those lines](https://github.com/fgnt/pb_bss/blob/master/pb_bss/evaluation/module_si_sdr.py#L40)?
Why not float32 for scale invariant SDR?

**Comment by boeddeker** [comment]
What is the motivation to use float32 for metrics?

Here our motivation:
We distinguish between algorithms and metrics.
For the algorithm, you can use any dtype (e.g. float16 for NNs).
When the quantization makes your score worse, it is ok, because your result is worse.
And using less bits for your numbers improved your runtime or you can increase your system.

When doing a quantization in a metric you may get better or worse scores without changing your algorithm quality.

We want to ensure that a calculated score is as precise as possible.
So with float64 we have a reasonable precision that we use to calculate a score.
To allow lower precision (float32 or float16) we want to first have a proof that it yields the same scores as float64 for any algorithm.

Since we do not want to make such a proof, we stay with float64.
Furthermore, using float32 instead of float64 makes the epsilon that prevents a division by zero much bigger (`2.2e-308` -> `1.2e-38`)
